procs:
  tauri:
    shell: >-
      bun run build-native-host &&
      RUST_BACKTRACE=full bun run tauri dev --no-watch
      --config src-tauri/tauri.dev.conf.json
      --config '{"build":{"beforeDevCommand":null}}'
    cwd: "<CONFIG_DIR>/../../../../../../apps/chord-tauri"
    autostart: true
    stop: SIGINT
  vite:
    shell: bun run vite-dev
    cwd: "<CONFIG_DIR>/../../../../../../apps/chord-tauri"
    autostart: true
    stop: SIGINT
