/*
 Generated by typeshare 1.13.4
*/

export type Key = string;

export interface AppPermissionsState {
	isAutostartEnabled?: boolean;
	isInputMonitoringEnabled?: boolean;
	isAccessibilityEnabled?: boolean;
}

export interface AppSettingsState {
	bundleIdsNeedingRelaunch: string[];
}

export interface ShortcutChord {
	keys: Key[];
}

/** Represents a parsed keyboard shortcut, e.g. "cmd+shift+n". */
export interface Shortcut {
	chords: ShortcutChord[];
}

export type ChordJsArgs = 
	| { type: "Values", value: Value[] }
	| { type: "Eval", value: string };

export interface ChordJsInvocation {
	export_name?: string;
	args: ChordJsArgs;
}

export interface Chord {
	keys: Key[];
	name: string;
	shortcut?: Shortcut;
	shell?: string;
	js?: ChordJsInvocation;
}

export interface ChorderState {
	keyBuffer: Key[];
	pressedChord?: Chord;
	activeChord?: Chord;
}

export interface GitRepo {
	owner: string;
	name: string;
	slug: string;
	url: string;
	localPath: string;
	headShortSha?: string;
}

