/*
 Generated by typeshare 1.13.4
*/

export type Key = string;

export interface AppPermissionsState {
	isAutostartEnabled?: boolean;
	isInputMonitoringEnabled?: boolean;
	isAccessibilityEnabled?: boolean;
}

export interface AppSettingsState {
	bundleIdsNeedingRelaunch: string[];
	showMenuBarIcon: boolean;
	showDockIcon: boolean;
	hideGuideByDefault: boolean;
}

/** The action that a chord can define. */
export type ChordAction = 
	| { type: "Shortcut", content: ShortcutChordAction }
	| { type: "Shell", content: ShellChordAction }
	| { type: "Emit", content: EmitChordAction };

/** A regular chord entry composed of static characters */
export interface Chord {
	rawTrigger: string;
	/** The keys that make up the chord (extracted from the TOML key) */
	trigger: { keys: string[] } | { regex: string };
	/** A mandatory chord name */
	name: string;
	/** The relative index of the chord inside the TOML file */
	index: number;
	/** A list of actions (as fallbacks) to execute when the chord is triggered */
	actions: ChordAction[];
}

/** The action that a chord task is meant to execute. */
export type ChordTaskAction = 
	| { type: "Shortcut", content: ShortcutChordAction }
	| { type: "Shell", content: ShellChordAction }
	| { type: "Handler", content: HandlerChordAction };

export interface ChordActionTask {
	action: ChordTaskAction;
	num_times: number;
}

export interface ChordHint {
	pattern: { keys: string[] } | { regex: string };
	rawPattern: string;
	description: string;
}

/** Currently only supports JavaScript handlers */
export interface ChordsFileHandler {
	file: string;
	args: Value[];
}

export interface ChordsFileImports {
	file: string;
}

export interface ChordsFile {
	name: string;
	meta: Record<string, string>;
	relpath: string;
	handlers: Record<string, ChordsFileHandler>;
	imports: ChordsFileImports[];
	chords: Chord[];
	chordHints: ChordHint[];
}

export interface ChordReference {
	chordsFilePath: PathBuf;
	chord: Chord;
}

export interface ChordPackage {
	/** The `name` property of the `package.json` file; defaults to the folder name if not present. */
	name: string;
	jsPackage?: ChordJsPackage;
	appChordsFiles: Record<PathBuf, ChordsFile>;
	globalChords: ChordReference[];
}

export interface ChordPackageManagerState {
	packages: ChordPackage[];
}

export interface ChorderState {
	keyBuffer: Key[];
	pressedChordKeys?: Key[];
	activeChordKeys?: Key[];
	isShiftPressed: boolean;
	isIndicatorVisible: boolean;
}

export interface DesktopAppMetadata {
	bundleId: string;
	displayName?: string;
	iconDataUrl?: string;
}

export interface DesktopAppManagerState {
	appsNeedingRelaunch: string[];
	appsMetadata: Record<string, DesktopAppMetadata>;
}

export interface EmitChordAction {
	event_key: string;
	args: Value[];
}

export interface FrontmostState {
	frontmostAppBundleId?: string;
}

export interface GitRepo {
	owner: string;
	name: string;
	slug: string;
	url: string;
	localPath: PathBuf;
	headShortSha?: string;
	pinnedRev?: string;
}

export interface GitReposState {
	repos: Record<string, GitRepo>;
}

/** Currently, we only support JavaScript handlers */
export interface HandlerChordAction {
	file: string;
	handler_args: Value[];
	event_args: Value[];
}

/**
 * Mapping of all the relevant files for a chord package.
 * 
 * We intentionally don't include the path of the package here to avoid leaking implementation
 * details about where the package is located on the filesystem.
 */
export interface RawChordPackage {
	/** The dirname is needed for inferring the chord package name when package.json isn't present */
	dirname: string;
	package_json_contents?: string;
	chords_files_contents: Record<PathBuf, string>;
	js_files_contents: Record<PathBuf, string>;
	bin_files_contents: Record<PathBuf, number[]>;
}

export interface ShellChordAction {
	command: string;
}

export interface SimulatedShortcutChord {
	keys: Key[];
}

export interface SimulatedShortcut {
	chords: SimulatedShortcutChord[];
}

export interface ShortcutChordAction {
	simulated_shortcut: SimulatedShortcut;
}

