// This file has been generated by TauRPC. Do not edit this file manually.


import { createTauRPCProxy as createProxy, type InferCommandOutput, type TauRpcResult, type UnlistenFn } from 'taurpc'
export type AppError = { Message: string };

export type GitRepo = {
	owner: string,
	name: string,
	slug: string,
	url: string,
	localAbspath: string,
	headShortSha: string | null,
	pinnedRev?: string | null,
};

export type GlobalShortcutMappingInfo = {
	shortcut: string,
	bundleId: string,
	hotkeyId: string,
};

export type LocalChordPackage = {
	path: string,
};

export type Result<T, E> = {
	ok: T,
	err: E,
};

export type StartupStatusInfo = {
	launchedViaAutostart: boolean,
	onboardingCompleted: boolean,
	shouldShowOnboarding: boolean,
};
const ARGS_MAP = {"":{"addGitRepo":["repo"],"addLocalChordFolder":["path"],"completeOnboarding":[],"getCurrentStates":[],"getStartupStatus":[],"listGlobalShortcutMappings":[],"listLocalChordFolders":[],"openAccessibilitySettings":[],"openInputMonitoringSettings":[],"pickLocalChordFolder":[],"quitApp":[],"relaunchApp":["bundle_id"],"removeGitRepo":["repo"],"removeGlobalShortcutMapping":["shortcut"],"removePlaceholderChordBinding":["file_path","sequence_template"],"resetDefaultChords":[],"setPlaceholderChordBinding":["file_path","sequence_template","sequence"],"syncGitRepo":["repo"],"toggleAutostart":[],"toggleDockIcon":[],"toggleHideGuideByDefault":[],"toggleMenuBarIcon":[],"updateGlobalShortcutMapping":["old_shortcut","new_shortcut"]}};

const RESULT_MAP = {"":{"addGitRepo":true,"addLocalChordFolder":true,"completeOnboarding":true,"getCurrentStates":true,"getStartupStatus":true,"listGlobalShortcutMappings":true,"listLocalChordFolders":true,"openAccessibilitySettings":false,"openInputMonitoringSettings":false,"pickLocalChordFolder":true,"quitApp":true,"relaunchApp":true,"removeGitRepo":true,"removeGlobalShortcutMapping":true,"removePlaceholderChordBinding":true,"resetDefaultChords":true,"setPlaceholderChordBinding":true,"syncGitRepo":true,"toggleAutostart":true,"toggleDockIcon":true,"toggleHideGuideByDefault":true,"toggleMenuBarIcon":true,"updateGlobalShortcutMapping":true}};

export type Router = {
	"": {
		addGitRepo: (repo: string) => Promise<GitRepo>,
		addLocalChordFolder: (path: string) => Promise<LocalChordPackage>,
		completeOnboarding: () => Promise<null>,
		getCurrentStates: () => Promise<string>,
		getStartupStatus: () => Promise<StartupStatusInfo>,
		listGlobalShortcutMappings: () => Promise<GlobalShortcutMappingInfo[]>,
		listLocalChordFolders: () => Promise<string[]>,
		openAccessibilitySettings: () => Promise<void>,
		openInputMonitoringSettings: () => Promise<void>,
		pickLocalChordFolder: () => Promise<string | null>,
		quitApp: () => Promise<null>,
		relaunchApp: (bundleId: string) => Promise<null>,
		removeGitRepo: (repo: string) => Promise<null>,
		removeGlobalShortcutMapping: (shortcut: string) => Promise<null>,
		removePlaceholderChordBinding: (filePath: string, sequenceTemplate: string) => Promise<null>,
		resetDefaultChords: () => Promise<null>,
		setPlaceholderChordBinding: (filePath: string, sequenceTemplate: string, sequence: string) => Promise<null>,
		syncGitRepo: (repo: string) => Promise<GitRepo>,
		toggleAutostart: () => Promise<null>,
		toggleDockIcon: () => Promise<null>,
		toggleHideGuideByDefault: () => Promise<null>,
		toggleMenuBarIcon: () => Promise<null>,
		updateGlobalShortcutMapping: (oldShortcut: string, newShortcut: string) => Promise<null>,
	},
};
export const createTauRPCProxy = () => createProxy<Router>({
  argsMap: ARGS_MAP,
  resultMap: RESULT_MAP,
  errorHandling: "throw",
})

// export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput, TauRpcResult }

