// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type AppError = { Message: string }

export type AppMetadataInfo = { bundleId: string; displayName: string | null; iconDataUrl: string | null }

export type AppNeedsRelaunchInfo = { bundleId: string; displayName: string | null }

export type GitRepo = { owner: string; name: string; slug: string; url: string; localPath: string; headShortSha: string | null }

export type GlobalShortcutMappingInfo = { shortcut: string; bundleId: string; hotkeyId: string }

export type LocalChordPackage = { path: string }

export type StartupStatusInfo = { launchedViaAutostart: boolean; onboardingCompleted: boolean; shouldShowOnboarding: boolean }

const ARGS_MAP = { '':'{"addGitRepo":["repo"],"addLocalChordFolder":["path"],"completeOnboarding":[],"getAppMetadata":["bundle_id"],"getCurrentState":["state_id"],"getStartupStatus":[],"listAppsNeedingRelaunch":[],"listGlobalShortcutMappings":[],"listLocalChordFolders":[],"openAccessibilitySettings":[],"openInputMonitoringSettings":[],"pickLocalChordFolder":[],"relaunchApp":["bundle_id"],"removeGlobalShortcutMapping":["shortcut"],"syncGitRepo":["repo"],"toggleAutostart":[]}' }
export type Router = { "": {addGitRepo: (repo: string) => Promise<GitRepo>, 
addLocalChordFolder: (path: string) => Promise<LocalChordPackage>, 
completeOnboarding: () => Promise<null>, 
getAppMetadata: (bundleId: string) => Promise<AppMetadataInfo>, 
getCurrentState: (stateId: string) => Promise<string>, 
getStartupStatus: () => Promise<StartupStatusInfo>, 
listAppsNeedingRelaunch: () => Promise<AppNeedsRelaunchInfo[]>, 
listGlobalShortcutMappings: () => Promise<GlobalShortcutMappingInfo[]>, 
listLocalChordFolders: () => Promise<LocalChordPackage[]>, 
openAccessibilitySettings: () => Promise<void>, 
openInputMonitoringSettings: () => Promise<void>, 
pickLocalChordFolder: () => Promise<string | null>, 
relaunchApp: (bundleId: string) => Promise<null>, 
removeGlobalShortcutMapping: (shortcut: string) => Promise<null>, 
syncGitRepo: (repo: string) => Promise<GitRepo>, 
toggleAutostart: () => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
