// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ActiveChordInfo = { scope: string; scopeKind: string; sequence: string; name: string; action: string }

export type AppMetadataInfo = { bundleId: string; displayName: string | null; iconDataUrl: string | null }

export type AppNeedsRelaunchInfo = { bundleId: string; displayName: string | null }

export type GitRepoInfo = { owner: string; name: string; slug: string; url: string; localPath: string; headShortSha: string | null }

export type GlobalShortcutMappingInfo = { shortcut: string; bundleId: string; hotkeyId: string }

export type LocalChordFolderInfo = { name: string; localPath: string }

const ARGS_MAP = { '':'{"addGitRepo":["repo"],"addLocalChordFolder":["path"],"listActiveChords":[],"listAppMetadata":["bundle_ids"],"listAppsNeedingRelaunch":[],"listGitRepos":[],"listGlobalShortcutMappings":[],"listLocalChordFolderChords":["path"],"listLocalChordFolders":[],"listMatchingChords":[],"listRepoChords":["repo"],"openAccessibilitySettings":[],"openInputMonitoringSettings":[],"pickLocalChordFolder":[],"relaunchApp":["bundle_id"],"removeGlobalShortcutMapping":["shortcut"],"syncGitRepo":["repo"]}' }
export type Router = { "": {addGitRepo: (repo: string) => Promise<GitRepoInfo>, 
addLocalChordFolder: (path: string) => Promise<LocalChordFolderInfo>, 
listActiveChords: () => Promise<ActiveChordInfo[]>, 
listAppMetadata: (bundleIds: string[]) => Promise<AppMetadataInfo[]>, 
listAppsNeedingRelaunch: () => Promise<AppNeedsRelaunchInfo[]>, 
listGitRepos: () => Promise<GitRepoInfo[]>, 
listGlobalShortcutMappings: () => Promise<GlobalShortcutMappingInfo[]>, 
listLocalChordFolderChords: (path: string) => Promise<ActiveChordInfo[]>, 
listLocalChordFolders: () => Promise<LocalChordFolderInfo[]>, 
listMatchingChords: () => Promise<ActiveChordInfo[]>, 
listRepoChords: (repo: string) => Promise<ActiveChordInfo[]>, 
openAccessibilitySettings: () => Promise<void>, 
openInputMonitoringSettings: () => Promise<void>, 
pickLocalChordFolder: () => Promise<string | null>, 
relaunchApp: (bundleId: string) => Promise<null>, 
removeGlobalShortcutMapping: (shortcut: string) => Promise<null>, 
syncGitRepo: (repo: string) => Promise<GitRepoInfo>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
