/*
 Generated by typeshare 1.13.4
*/

export type Key = string;

/** The raw keys the user inputs to match a Chord trigger */
export type ChordInput = Key[];

export type FilePathslug = string;

export type TomlValue = any;

export interface AppPermissionsState {
	isAutostartEnabled?: boolean;
	isInputMonitoringEnabled?: boolean;
	isAccessibilityEnabled?: boolean;
}

export interface AppSettingsState {
	bundleIdsNeedingRelaunch: string[];
	showMenuBarIcon: boolean;
	showDockIcon: boolean;
	isChordPanelHiddenByDefault: boolean;
}

/** The action that a chord can define. */
export type ChordAction = 
	| { type: "shortcut", content: ShortcutChordAction }
	| { type: "shell", content: ShellChordAction }
	| { type: "emit", content: EmitChordAction };

/** A mapping from a sequence (or pattern) of keys to a series of actions. */
export interface Chord {
	rawTrigger: string;
	/** The keys that make up the chord (extracted from the TOML key) */
	trigger: { keys: string[] } | { regex: string };
	/** A mandatory chord name */
	name: string;
	/** The relative index of the chord inside the TOML file */
	index: number;
	/** A list of actions (as fallbacks) to execute when the chord is triggered */
	actions: ChordAction[];
}

export interface ChordInputEvent {
	/** The sequence of keys the user pressed to trigger the chord. */
	input: ChordInput;
	/** The ID of the application the chord execution applied to. */
	applicationId?: string;
}

/** The action that a chord task is meant to execute. */
export type ChordTaskAction = 
	| { type: "shortcut", content: ShortcutChordAction }
	| { type: "shell", content: ShellChordAction }
	| { type: "handler", content: HandlerChordAction };

export interface ChordActionTask {
	packageName: string;
	initiatorFilePathslug: FilePathslug;
	/** The event that triggered the task. */
	event: ChordInputEvent;
	action: ChordTaskAction;
	numTimes: number;
}

export interface ChordHint {
	pattern: { keys: string[] } | { regex: string };
	rawPattern: string;
	description: string;
}

export interface ChordInputState {
	/**
	 * The keys a user has pressed for a chord but not yet executed. Think of it as the equivalent
	 * of an HTML <input />'s `value`. Always cleared when executed.
	 */
	input: ChordInput;
	/** The chord currently being pressed down. */
	pressedInputEvent?: ChordInputEvent;
	/** The chord that is "active" */
	selectedInputEvent?: ChordInputEvent;
}

export interface ChordJsPackage {
	name: string;
	files: Record<FilePathslug, string>;
}

export interface NativeLibraryArtifact {
	sha256: string;
	size: number;
}

/**
 * The validated, materialized native artifacts of one package. Mirrors `ChordJsPackage`:
 * libraries are keyed by pathslug (`target/<triple>/swift/menu/menu.dylib`) and resolved
 * relative to the chords file that references them so bundled (nested) packages resolve to
 * their own libraries. The whole `target/` subtree is materialized together so libraries can
 * reference vendored sibling libraries via `@loader_path`.
 */
export interface ChordNativePackage {
	name: string;
	/** Hash of the materialized artifact tree. */
	treeSha256: string;
	libraries: Record<FilePathslug, NativeLibraryArtifact>;
}

/** Which backend executes a handler. Omitted in TOML means JavaScript for backward compatibility. */
export enum ChordsFileHandlerKind {
	Js = "js",
	/**
	 * A prebuilt library at `target/<triple>/swift/<name>/<name>.<dylib|dll|so>` exporting
	 * `chord_native_run_v1`, executed inside the isolated `chord-native-host` process.
	 */
	Native = "native",
}

export interface ChordsFileHandler {
	kind?: ChordsFileHandlerKind;
	/**
	 * JS: a path inside `js/` (e.g. `menu.js`). Native: a logical module name without
	 * extension (e.g. `menu` -> `target/<triple>/swift/menu/menu.dylib`).
	 */
	file: string;
	args?: any[];
}

/** Currently, we only support overriding meta, but might support overriding chords in the future. */
export interface ChordsFileImportOverride {
	meta: Record<string, TomlValue>;
}

export interface ChordsFileImport {
	file: string;
	override?: ChordsFileImportOverride;
}

export interface RawChordsFile {
	name: string;
	meta?: Record<string, TomlValue>;
	handlers?: Record<string, ChordsFileHandler>;
	chords?: Record<string, TomlValue>;
	imports?: ChordsFileImport[];
}

export interface CompiledChordsFileHandler {
	event: string;
	handlerId: string;
	kind: ChordsFileHandlerKind;
}

/** A chords file that has imports inlined. */
export interface CompiledChordsFile {
	name: string;
	pathslug: FilePathslug;
	meta: Record<string, TomlValue>;
	handlers: CompiledChordsFileHandler[];
	chords: Chord[];
	chordHints: ChordHint[];
}

export interface ChordReference {
	packageName: string;
	chordsFilePathslug: FilePathslug;
	chord: Chord;
}

export interface ChordPackage {
	/** The `name` property of the `package.json` file; defaults to the folder name if not present. */
	name: string;
	jsPackage?: ChordJsPackage;
	nativePackage?: ChordNativePackage;
	rawChordsFiles: Record<FilePathslug, RawChordsFile>;
	compiledChordsFiles: Record<FilePathslug, CompiledChordsFile>;
	globalChords: ChordReference[];
}

export interface ChordPackageManagerState {
	packages: ChordPackage[];
}

export interface ChordPackageStoreEntry {
	priority: number;
}

export interface ChordPackageStoreState {
	entries: Record<string, ChordPackageStoreEntry>;
}

export interface ChordPanelState {
	isVisible: boolean;
}

export interface DesktopAppMetadata {
	bundleId: string;
	displayName?: string;
	iconDataUrl?: string;
}

export interface DesktopAppManagerState {
	appsNeedingRelaunch: string[];
	appsMetadata: Record<string, DesktopAppMetadata>;
}

export interface EmitChordAction {
	eventKey: string;
	args: any;
}

export interface FrontmostState {
	frontmostAppBundleId?: string;
}

export interface GitRepo {
	owner: string;
	name: string;
	slug: string;
	url: string;
	localAbspath: string;
	headShortSha?: string;
	pinnedRev?: string;
}

export interface GitReposState {
	repos: Record<string, GitRepo>;
}

export interface HandlerChordAction {
	/**
	 * JS: key in the QuickJS `__RUST_HANDLER_REGISTRY`. Native: registration id in the
	 * native host's active generation.
	 */
	handlerId: string;
	kind: ChordsFileHandlerKind;
	eventArgs: any[];
}

export interface KeyboardState {
	isCapsPressed: boolean;
	isShiftPressed: boolean;
}

export interface ParsedChordsFile {
	name: string;
	meta: Record<string, TomlValue>;
	handlers: Record<string, ChordsFileHandler>;
	imports: ChordsFileImport[];
	chords: Chord[];
	chordHints: ChordHint[];
	/**
	 * This is the object exposed to the JS handler. This maximizes compatibility so that even if
	 * our internal representation changes, a user's scripts will continue to work because it only
	 * depends on the actual TOML structure and not how we parse it.
	 */
	raw: RawChordsFile;
}

/**
 * Mapping of all the relevant files for a chord package.
 * 
 * We intentionally don't include the path of the package here to avoid leaking implementation
 * details about where the package is located on the filesystem.
 */
export interface RawChordPackage {
	/** The dirname is needed for inferring the chord package name when package.json isn't present */
	dirname: string;
	packageJsonContents?: string;
	chordsFilesContents: Record<FilePathslug, string>;
	jsFilesContents: Record<FilePathslug, string>;
	binFilesContents: Record<FilePathslug, number[]>;
	/**
	 * Prebuilt native build artifacts for the current target triple from the package's
	 * top-level `target/` directory (`target/<triple>/swift/<name>/...`), keyed by pathslug.
	 */
	nativeFilesContents: Record<FilePathslug, number[]>;
}

export interface ShellChordAction {
	command: string;
}

export interface SimulatedShortcutChord {
	keys: Key[];
}

export interface SimulatedShortcut {
	chords: SimulatedShortcutChord[];
}

export interface ShortcutChordAction {
	simulatedShortcut: SimulatedShortcut;
}

export enum AppModeState {
	Idle = "idle",
	Chord = "chord",
}

